FROM node:12.14.1-alpine

RUN mkdir -p /opt/frontend
WORKDIR /opt/frontend

ADD package.json yarn.lock /opt/frontend/

RUN apk add --no-cache --virtual .build-deps alpine-sdk python && \
    yarn && \
    apk del .build-deps

#ARG PUBLIC_PWA_GATEWAY_URI
#ENV PUBLIC_PWA_GATEWAY_URI=${PUBLIC_PWA_GATEWAY_URI}
#ARG PUBLIC_KEYCLOAK_URI
#ENV PUBLIC_KEYCLOAK_URI=${PUBLIC_KEYCLOAK_URI}
#ARG KEYCLOAK_AUTH_REALM
#ENV KEYCLOAK_AUTH_REALM=${KEYCLOAK_AUTH_REALM}
#ARG KEYCLOAK_FRONTEND_CLIENT_ID
#ENV KEYCLOAK_FRONTEND_CLIENT_ID=${KEYCLOAK_FRONTEND_CLIENT_ID}

#ARG PWA_GATEWAY_URI
#ENV PWA_GATEWAY_URI=${PWA_GATEWAY_URI}
#ARG KEYCLOAK_URI
#ENV KEYCLOAK_URI=${KEYCLOAK_URI}

ARG SERVICE_PORT
ENV SERVICE_PORT=${SERVICE_PORT}

ARG BUILD_LANGUAGE
ENV BUILD_LANGUAGE=${BUILD_LANGUAGE}

ENV RUNNING_ENV="docker"

ADD . .
#RUN yarn run build

EXPOSE ${SERVICE_PORT}

CMD ["npm", "run", "build-and-start"]
