version: "3.4"
services:
  frontend:
    build:
      context: ./
      args:
        SERVICE_PORT: ${SERVICE_PORT}
        BUILD_LANGUAGE: ${PWA_BUILD_LANGUAGE}
    image: "${DOCKER_REGISTRY}wikitolearn/frontend-${PWA_BUILD_LANGUAGE}:${DOCKER_IMAGE_FRONTEND_TAG}"
#    deploy:
#      mode: global
#      update_config:
#        parallelism: 1
#        delay: 120s
#        order: start-first
    environment:
      PUBLIC_PWA_GATEWAY_URI: ${PUBLIC_PWA_GATEWAY_URI}
      PUBLIC_KEYCLOAK_URI: ${PUBLIC_KEYCLOAK_URI}
      KEYCLOAK_AUTH_REALM: ${KEYCLOAK_AUTH_REALM}
      KEYCLOAK_FRONTEND_CLIENT_ID: ${KEYCLOAK_FRONTEND_CLIENT_ID}
      PWA_GATEWAY_URI: ${PWA_GATEWAY_URI}
      KEYCLOAK_URI: ${KEYCLOAK_URI}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
