version: "3.4"
services:
  frontend:
    build:
      context: ./
      args:
        SERVICE_PORT: ${SERVICE_PORT}
        CLIENT_API_HOSTNAME: ${CLIENT_API_HOSTNAME}
        CLIENT_AUTH_HOSTNAME: ${CLIENT_AUTH_HOSTNAME}
        CLIENT_AUTH_REALM: ${CLIENT_AUTH_REALM}
        CLIENT_AUTH_ID: ${CLIENT_AUTH_ID}
        SERVER_API_HOSTNAME: ${SERVER_API_HOSTNAME}
        SERVER_AUTH_HOSTNAME: ${SERVER_AUTH_HOSTNAME}
        BUILD_LANGUAGE: ${PWA_BUILD_LANGUAGE}
    image: "${DOCKER_REGISTRY}wikitolearn/frontend-${PWA_BUILD_LANGUAGE}"
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"

