version: "3.4"
services:
  pwa:
    build:
      context: ./
      args:
        SERVICE_PORT: ${SERVICE_PORT}
        CLIENT_API_HOSTNAME: ${CLIENT_API_HOSTNAME}
        CLIENT_AUTH_HOSTNAME: ${CLIENT_AUTH_HOSTNAME}
        CLIENT_AUTH_REALM: ${CLIENT_AUTH_REALM}
        CLIENT_AUTH_ID: ${CLIENT_AUTH_ID}
        SERVER_API_HOSTNAME: ${SERVER_API_HOSTNAME}
        SERVER_AUTH_HOSTNAME: ${SERVER_AUTH_HOSTNAME}
    image: wikitolearn/pwa
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      CLIENT_API_HOSTNAME: ${CLIENT_API_HOSTNAME}
      CLIENT_AUTH_HOSTNAME: ${CLIENT_AUTH_HOSTNAME}
      CLIENT_AUTH_REALM: ${CLIENT_AUTH_REALM}
      CLIENT_AUTH_ID: ${CLIENT_AUTH_ID}
      SERVER_API_HOSTNAME: ${SERVER_API_HOSTNAME}
      SERVER_AUTH_HOSTNAME: ${SERVER_AUTH_HOSTNAME}
      SERVER_PORT: ${SERVICE_PORT}

